name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Pull updates from transforms submodule and commit
        git submodule init
        git submodule update --remote transforms
        git add transforms
        git config --global user.email "kjgalli@radium.ncsc.mil"
        git config --global user.name "Kevin G"
        git commit
        echo Done
 
